name: wordpress_api
description: A WordPress REST API client for dart with support for WooCommerce
  and custom namespaces.
version: 1.1.0
homepage: https://github.com/dhmgroup/dart-wp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  dio: ^5.3.0
  html: ^0.15.4
  logger: ^1.4.0
dev_dependencies:
  lints: ^2.0.1
